apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: frontend
spec:
  replica: 3
  selector:
    matchLabels:
      type: front-end
  template:
     metadata:
        name: myapp_pod
        labels:
           app: myapp
           type: frontend
        spec:
          containers:
              - name: nginx-container
                image: nginx

  
